//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantaiko.Modularity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kantaiko.Modularity.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module constructor can only accept IConfiguration and IHostEnvironment as parameters.
        /// </summary>
        internal static string InvalidModuleParameter {
            get {
                return ResourceManager.GetString("InvalidModuleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; is not a valid module type..
        /// </summary>
        internal static string InvalidModuleType {
            get {
                return ResourceManager.GetString("InvalidModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module cannot contain multiple constructors.
        /// </summary>
        internal static string ModuleCannotContainMultipleConstructors {
            get {
                return ResourceManager.GetString("ModuleCannotContainMultipleConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module must contain accessible constructor.
        /// </summary>
        internal static string ModuleMustContainAccessibleConstructor {
            get {
                return ResourceManager.GetString("ModuleMustContainAccessibleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to construct the module of type &quot;{0}&quot;: {1}..
        /// </summary>
        internal static string UnableToConstructModule {
            get {
                return ResourceManager.GetString("UnableToConstructModule", resourceCulture);
            }
        }
    }
}
